#### Comparsion between vector and Array

In [37]:
import numpy as np 
a = np.random.randn(5)
print("The random array is:\n",a,"\n")
print("The rank of array is:\n",a.shape)

The random array is:
 [-0.73270408  0.72165214 -1.03577265 -0.34931862  0.09245557] 

The rank of array is:
 (5,)


In [40]:
# we estimate that the result is array but the run is not like that bec. this not vector
print(np.dot(a,a.T))



[[ 9.2171619  -2.83950024]
 [-2.83950024  8.36108411]]


In [41]:
#print it as array
a = np.random.randn(5,1)
print("The vector is : \n",a)
# Col Vector
print("\n When we make it again : \n",a.T)

The vector is : 
 [[ 0.65168314]
 [ 0.33218217]
 [-0.16713646]
 [ 1.34978694]
 [-0.05464618]]

 When we make it again : 
 [[ 0.65168314  0.33218217 -0.16713646  1.34978694 -0.05464618]]


In [36]:
# check  the deminsions again
print(np.dot(a,a.T))

[[ 0.68560091 -0.10651146 -0.93333169 -0.98477959  0.39274236]
 [-0.10651146  0.01654708  0.14499765  0.15299034 -0.06101445]
 [-0.93333169  0.14499765  1.27057597  1.34061374 -0.53465345]
 [-0.98477959  0.15299034  1.34061374  1.4145122  -0.56412508]
 [ 0.39274236 -0.06101445 -0.53465345 -0.56412508  0.2249801 ]]


In [48]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print("The shape after dot : \n",c.shape)

The shape after dot : 
 (12288, 45)


In [50]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print(c.shape)

[[-0.97075522  0.02759618  0.11134774]
 [ 0.4838635   0.48278208 -0.37396074]
 [ 1.56650437  3.68995075  1.45214361]]
(3, 3)


In [53]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)
